#pragma once

#include "emulator/iss.h"
#include "emulator/config.h"
#include <memory>
#include <string>

namespace emulator {

// Verilator wrapper around the RTL core. Implements the ISS interface so the
// existing shell, loader, and difftest harness can drive the processor.
class RtlISS : public ISS {
public:
    // top_module_dir is the directory containing the Verilated model headers
    // (e.g. "obj_dir" generated by verilator --cc).
    explicit RtlISS(Config cfg = {});
    ~RtlISS() override;

    void reset(u32 reset_addr = 0x20000000) override;
    bool step_cycle() override;
    bool step_inst(CommitEvent& out) override;

    u32 pc() const override;
    u32 reg(u32 idx) const override;
    u32 csr(u32 addr) const override;

    u32 read_mem(u32 addr, u32 size) override;
    void write_mem(u32 addr, u32 size, u32 data) override;

    bool load_bin(const std::string& path, u32 addr) override;
    bool load_elf(const std::string& path) override;

    bool save_checkpoint(const std::string& path) override;
    bool load_checkpoint(const std::string& path) override;

    void set_log_level(int level) override;

    u64 cycle() const;

    // Enable VCD tracing to the given file.
    void enable_trace(const std::string& path);
    void disable_trace();

private:
    class Impl;
    std::unique_ptr<Impl> impl_;
};

} // namespace emulator
